import type { Metadata } from "next";
import { Roboto, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/Sidebar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen w-screen overflow-x-hidden">
      <body
        className={`${roboto.variable} ${jetbrainsMono.variable} antialiased h-full w-full`}
      >
        <div className="flex flex-col h-full">
          {/* ✅ Navbar fixed at the top */}


          {/* ✅ Main layout area — sidebar below navbar */}
          <SidebarProvider>
            <div className="flex overflow-hidden">
              {/* Sidebar on the left */}
              <div className="absolute">
                <AppSidebar />
              </div>


              {/* Main content area */}
              <main className="overflow-x-hidden ">
                {/* <SidebarTrigger /> */}
                <div className='flex justify-center h-screen w-screen overflow-y-scroll relative bg-gradient-to-br from-sky-100 via-white to-sky-200'>
                  <div className='max-w-[1200px] w-full'>
                    {children}
                  </div>
                </div>
              </main>
            </div>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
