import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen w-screen overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full`}
      >
        <div className="flex flex-col h-full">
          {/* ✅ Navbar fixed at the top */}


          {/* ✅ Main layout area — sidebar below navbar */}
          <SidebarProvider>
            <div className="flex overflow-hidden">
              {/* Sidebar on the left */}
              <div className="absolute">
                <AppSidebar />
              </div>


              {/* Main content area */}
              <main className="overflow-x-hidden">
                {/* <SidebarTrigger /> */}
                <div className='flex justify-center h-screen w-screen overflow-y-scroll bg-white relative'>
                  <div className='max-w-[1200px] w-full'>
                    {children}
                  </div>
                </div>
              </main>
            </div>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
