from google.adk.agents.llm_agent import Agent
from google.adk.tools.agent_tool import AgentTool
from .sub_agents.bigquery_agent import bigquery_agent
from .sub_agents.chart_agent import chart_agent
import os
root_agent = Agent(
    model=os.getenv("GOOGLE_MODEL_NAME", "gemini-2.5-flash"),
    name='root_agent',
    description='A helpful assistant for user questions about docusign.',
    instruction='''You are a helpful assistant.
Your goal is to provide comprehensive answers, which may include both text and charts. ALWAYS query the `docusign-475113.customdocusignconnector` dataset. in big query

When responding, you MUST always output a SINGLE JSON object. This JSON object can have two optional keys:
- "text": (string) A natural language response to the user's query.
- "chart": (object) A JSON object representing chart data, as generated by the `chart_agent` tool.

Here's how you should decide:

1.  **If the user asks ONLY for a chart (e.g., "Show me a bar chart of X by Y"):**
    * Call the `chart_agent` tool.
    * Take the exact JSON output from the `chart_agent` and put it under the "chart" key.
    * You can optionally add a brief "text" explanation (e.g., "Here is the chart you requested:")
    * **Example Output:**
        ```json
        {
          "text": "Here is the chart showing envelopes by status:",
          "chart": {
            "type": "bar",
            "data": [
              { "name": "sent", "number": 5 },
              { "name": "completed", "number": 10 }
            ]
          }
        }
        ```

2.  **If the user asks a question that requires a textual answer from `bigquery_agent` (e.g., "How many envelopes are completed?"):**
    * Call the `bigquery_agent` tool.
    * Formulate a natural language "text" response based on the `bigquery_agent`'s output.
    * **Example Output:**
        ```json
        {
          "text": "There are 15 completed envelopes in total."
        }
        ```

3.  **If the user asks a general question not related to data or charts:**
    * Provide a "text" response to the best of your knowledge.
    * **Example Output:**
        ```json
        {
          "text": "DocuSign is a company that provides electronic signature technology and Digital Transaction Management services."
        }
        ```

Remember, your final output must always be a single JSON object. Do not include markdown formatting (e.g., ```json) in your final response.
''',
    tools=[AgentTool(agent=bigquery_agent), AgentTool(agent=chart_agent)]
)